[package]
name = "access_remove_locked_list"
version = "0.1.0"
authors = ["Jiahao XU <Jiahao_XU@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
async = ["tokio"]
permutation_testing = ["loom"]

[dependencies]
tokio = { version = "1.9", features = ["sync"], optional = true }
loom = { version = "0.5.1", optional = true }
